This module provides a single class "SpringReloader" that is used by the    ReloadingSpringFilter to reload a Spring web application context.    In order not to run into NoClassDefFoundErrors, is is important that this    class is loaded through the reloading classloader.